[package]
name = "brb_dt_orswot"
version = "0.1.0"
authors = ["David Rusu <davidrusu.me@gmail.com>"]
edition = "2018"
license = "MIT OR BSD-3-Clause"

[dependencies]
crdts = "4.0.0"
brb = { path = "../brb" }
serde = "1.0.106"

